name: dependent jobs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prep build
        run: date
      - name: Build execution
        run: |
          echo "Building application..."
          sleep 5

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prep test
        run: pwd
      - name: Test execution
        run: |
          echo "Running tests..."
          sleep 5

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Prep deploy
        run: env
      - name: Deploy execution
        run: |
          echo "Deploying application..."
          sleep 5
